name: screenshots
favicon: null
layout_spectrum: 0.24374
typography_spectrum: 0.4674670584499836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#ffffff'
    - '#525252'
    - '#b4b4b4'
    - '#969696'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.9781871754676104
purpose: []
